// ═══════════════════════════════════════════════════════════════════
// All Arabic UI strings — never hardcode in components
// ═══════════════════════════════════════════════════════════════════

export const AR = {
  // App
  appName: 'منصة إترا للتدريب التقني',
  appNameEn: 'ETRA Training Portal',
  company: 'شركة إترا للتقنية',

  // Auth
  login: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  forgotPassword: 'نسيت كلمة المرور؟',
  resetPassword: 'إعادة تعيين كلمة المرور',
  sendResetLink: 'إرسال رابط الاستعادة',
  backToLogin: 'العودة لتسجيل الدخول',
  welcomeBack: 'مرحباً بك في',
  loginSubtitle: 'سجّلي دخولك للوصول إلى منصة التدريب',
  emailPlaceholder: 'أدخلي بريدك الإلكتروني',
  passwordPlaceholder: 'أدخلي كلمة المرور',
  showPassword: 'إظهار كلمة المرور',
  hidePassword: 'إخفاء كلمة المرور',
  loggingIn: 'جارٍ تسجيل الدخول...',
  loginSuccess: 'تم تسجيل الدخول بنجاح',
  loginError: 'بيانات الدخول غير صحيحة',

  // Navigation — Trainee
  navDashboard: 'الرئيسية',
  navLearning: 'مسار التعلم',
  navQuizzes: 'الاختبارات',
  navAssignments: 'المهام',
  navTickets: 'تذاكري',
  navGrades: 'درجاتي',
  navAttendance: 'حضوري',
  navAnnouncements: 'الإعلانات',
  navProfile: 'ملفي الشخصي',

  // Navigation — Admin
  navAdminDashboard: 'لوحة التحكم',
  navTrainees: 'المتدربات',
  navContent: 'إدارة المحتوى',
  navTicketMgmt: 'إدارة التذاكر',
  navAttendanceMgmt: 'الحضور',
  navGradesMgmt: 'الدرجات',
  navReports: 'التقارير',
  navSettings: 'الإعدادات',

  // Dashboard
  hello: 'مرحباً',
  currentWeek: 'أسبوع التدريب الحالي',
  overallProgress: 'نسبة الإكمال الكلية',
  completedLessons: 'دروس مكتملة',
  pendingAssignments: 'مهام معلقة',
  openTickets: 'تذاكر مفتوحة',
  avgQuizScore: 'متوسط الاختبارات',
  continuelearning: 'أكمل التعلم →',
  latestFeedback: 'آخر تغذية راجعة من المشرف',
  weeklyProgress: 'التقدم الأسبوعي',
  recentAnnouncements: 'الإعلانات الأخيرة',
  activeTrainees: 'المتدربات النشطات',
  avgCompletion: 'متوسط نسبة الإكمال',
  ticketsResolved: 'تذاكر محلولة',
  assignmentsReview: 'مهام بانتظار المراجعة',
  quickActions: 'إجراءات سريعة',
  createTicket: 'إنشاء تذكرة',
  addAnnouncement: 'إضافة إعلان',
  recordAttendance: 'تسجيل الحضور',

  // Learning
  week: 'الأسبوع',
  module: 'الوحدة',
  lesson: 'الدرس',
  minutes: 'دقيقة',
  completed: 'مكتمل',
  inProgress: 'قيد التقدم',
  notStarted: 'لم تبدأ',
  locked: 'مقفل',
  markComplete: 'تحديد كمكتمل',
  objectives: 'الأهداف التعليمية',
  practicalActivity: 'النشاط التطبيقي',
  nextLesson: 'الدرس التالي',
  prevLesson: 'الدرس السابق',

  // Quizzes
  quiz: 'اختبار',
  startQuiz: 'بدء الاختبار',
  submitAnswer: 'إرسال الإجابة',
  nextQuestion: 'السؤال التالي',
  prevQuestion: 'السؤال السابق',
  finishQuiz: 'إنهاء الاختبار',
  question: 'سؤال',
  of: 'من',
  score: 'النتيجة',
  passed: 'ناجح',
  failed: 'راسب',
  passingScore: 'درجة النجاح',
  attempts: 'المحاولات',
  timeLimit: 'الوقت المحدد',
  timeRemaining: 'الوقت المتبقي',
  quizResult: 'نتيجة الاختبار',
  tryAgain: 'إعادة المحاولة',
  viewHistory: 'عرض السجل',
  mcq: 'اختيار من متعدد',
  scenario: 'سيناريو عملي',
  truefalse: 'صح أو خطأ',
  ordering: 'رتّب الخطوات',
  correct: 'إجابة صحيحة',
  incorrect: 'إجابة خاطئة',
  scenarioContext: 'الموقف:',

  // Assignments
  assignment: 'مهمة',
  dueDate: 'تاريخ التسليم',
  maxScore: 'الدرجة القصوى',
  submitAssignment: 'تسليم المهمة',
  yourAnswer: 'إجابتك',
  attachFile: 'إرفاق ملف',
  submitted: 'مسلّمة',
  graded: 'مقيّمة',
  draft: 'مسودة',
  resubmit: 'إعادة التسليم',
  feedback: 'التغذية الراجعة',
  grade: 'الدرجة',
  saveDraft: 'حفظ كمسودة',

  // Tickets
  ticket: 'تذكرة',
  tickets: 'التذاكر',
  myTickets: 'تذاكري',
  ticketNumber: 'رقم التذكرة',
  ticketTitle: 'عنوان التذكرة',
  description: 'الوصف',
  requesterName: 'اسم مقدم الطلب',
  requesterDept: 'القسم',
  deviceName: 'اسم الجهاز',
  category: 'التصنيف',
  priority: 'الأولوية',
  status: 'الحالة',
  assignedTo: 'مسندة إلى',
  createdAt: 'تاريخ الإنشاء',
  dueAt: 'الموعد النهائي',
  slaTimer: 'مؤشر SLA',
  diagnosis: 'التشخيص الأولي',
  troubleshootingSteps: 'خطوات الاستكشاف',
  rootCause: 'السبب الجذري',
  resolution: 'الحل النهائي',
  addNote: 'إضافة ملاحظة',
  addStep: 'إضافة خطوة',
  submitResolution: 'تسليم الحل',
  activityTimeline: 'سجل النشاط',
  internalNote: 'ملاحظة داخلية',
  adminOnly: 'للمشرف فقط',
  expectedDiagnosis: 'التشخيص المتوقع',
  expectedSteps: 'الخطوات المتوقعة',
  expectedResolution: 'الحل المتوقع',
  evaluateTicket: 'تقييم التذكرة',
  diagnosisScore: 'درجة التشخيص',
  stepsScore: 'درجة الخطوات',
  resolutionScore: 'درجة الحل',
  totalScore: 'المجموع',
  closeTicket: 'إغلاق التذكرة',
  reopenTicket: 'إعادة فتح التذكرة',

  // Ticket Status
  statusNew: 'جديدة',
  statusAssigned: 'مسندة',
  statusAnalyzing: 'قيد التحليل',
  statusWaiting: 'بانتظار المستخدم',
  statusResolved: 'محلولة',
  statusClosed: 'مغلقة',
  statusReopened: 'معاد فتحها',

  // Ticket Priority
  priorityLow: 'منخفضة',
  priorityMedium: 'متوسطة',
  priorityHigh: 'عالية',
  priorityCritical: 'حرجة',

  // Ticket Category
  catHardware: 'العتاد',
  catSoftware: 'البرمجيات',
  catWindows: 'ويندوز',
  catNetwork: 'الشبكة',
  catPrinter: 'الطابعة',
  catAccount: 'الحساب',
  catPassword: 'كلمة المرور',
  catOther: 'أخرى',

  // Attendance
  attendance: 'الحضور',
  present: 'حاضر',
  late: 'متأخر',
  absent: 'غائب',
  excused: 'معذور',
  remote: 'عن بعد',
  inperson: 'حضوري',
  date: 'التاريخ',
  session: 'الجلسة',
  notes: 'ملاحظات',
  recordAttendanceAction: 'تسجيل الحضور',

  // Announcements
  announcement: 'إعلان',
  announcements: 'الإعلانات',
  normal: 'عادي',
  important: 'مهم',
  urgent: 'عاجل',
  publishedAt: 'تاريخ النشر',
  expiresAt: 'تاريخ الانتهاء',

  // Grades
  grades: 'الدرجات',
  lessonsScore: 'درجة الدروس',
  quizzesScore: 'درجة الاختبارات',
  assignmentsScore: 'درجة المهام',
  ticketsScore: 'درجة التذاكر',
  attendanceScore: 'درجة الحضور',
  totalGrade: 'المجموع الكلي',

  // Common actions
  save: 'حفظ',
  cancel: 'إلغاء',
  edit: 'تعديل',
  delete: 'حذف',
  view: 'عرض',
  add: 'إضافة',
  create: 'إنشاء',
  update: 'تحديث',
  search: 'بحث',
  filter: 'تصفية',
  export: 'تصدير',
  loading: 'جارٍ التحميل...',
  saving: 'جارٍ الحفظ...',
  noData: 'لا توجد بيانات',
  noResults: 'لا توجد نتائج',
  error: 'خطأ',
  success: 'نجاح',
  confirm: 'تأكيد',
  back: 'رجوع',
  close: 'إغلاق',
  all: 'الكل',
  yes: 'نعم',
  no: 'لا',
  optional: 'اختياري',
  required: 'مطلوب',
  from: 'من',
  to: 'إلى',
  days: 'يوم',
  hours: 'ساعة',
  mins: 'دقيقة',

  // Simulators
  hardwareSimulator: 'محاكي مكونات الحاسب',
  networkSimulator: 'محاكي الشبكة',
  identifyComponent: 'تعرف على المكون',
  selectCorrectComponent: 'اختر المكون الصحيح',
  orderSteps: 'رتب خطوات التجميع',
  testConnection: 'اختبر الاتصال',
  connectionSuccess: '✓ اتصال ناجح',
  connectionFail: '✗ خطأ في الإعداد',
  dragToCanvas: 'اسحب الأجهزة إلى اللوحة',
  configureDevice: 'إعداد الجهاز',
  assignIP: 'تعيين عنوان IP',

  // Profile
  profile: 'الملف الشخصي',
  fullName: 'الاسم الكامل',
  changePassword: 'تغيير كلمة المرور',
  currentPassword: 'كلمة المرور الحالية',
  newPassword: 'كلمة المرور الجديدة',
  confirmPassword: 'تأكيد كلمة المرور',
  updateProfile: 'تحديث الملف',

  // Empty states
  emptyTickets: 'لا توجد تذاكر مسندة إليك حالياً',
  emptyLessons: 'لا توجد دروس متاحة في هذه الوحدة',
  emptyQuizzes: 'لا توجد اختبارات متاحة',
  emptyAssignments: 'لا توجد مهام معلقة',
  emptyAnnouncements: 'لا توجد إعلانات',
  emptyGrades: 'لا توجد درجات مسجلة',

  // Errors
  errorGeneric: 'حدث خطأ غير متوقع. يرجى المحاولة مجدداً.',
  errorNetwork: 'تعذّر الاتصال بالخادم. يرجى التحقق من اتصالك بالإنترنت.',
  errorUnauthorized: 'غير مصرح لك بالوصول.',
  errorNotFound: 'الصفحة المطلوبة غير موجودة.',
};

// ── Ticket label helpers ──────────────────────────────────────────
export const TICKET_STATUS_LABELS: Record<string, string> = {
  new: AR.statusNew,
  assigned: AR.statusAssigned,
  analyzing: AR.statusAnalyzing,
  waiting: AR.statusWaiting,
  resolved: AR.statusResolved,
  closed: AR.statusClosed,
  reopened: AR.statusReopened,
};

export const TICKET_PRIORITY_LABELS: Record<string, string> = {
  low: AR.priorityLow,
  medium: AR.priorityMedium,
  high: AR.priorityHigh,
  critical: AR.priorityCritical,
};

export const TICKET_CATEGORY_LABELS: Record<string, string> = {
  hardware: AR.catHardware,
  software: AR.catSoftware,
  windows: AR.catWindows,
  network: AR.catNetwork,
  printer: AR.catPrinter,
  account: AR.catAccount,
  password: AR.catPassword,
  other: AR.catOther,
};

export const ATTENDANCE_STATUS_LABELS: Record<string, string> = {
  present: AR.present,
  late: AR.late,
  absent: AR.absent,
  excused: AR.excused,
};
